image:
  ubuntu19_robocomp_installed
matrix:
  - env: SCRIPT="robocomp_compilation"
  - env: ABSTRUSE_BUILD_DIR="~/robocomp/components/
branches:
  - euroage*
script:
  - ls robocomp/components/euroage-tv/components/tvgames/
