image:
  robocomp_dependences_20.04
matrix:
  - env: SCRIPT="robocomp_compilation" ABSTRUSE_BUILD_DIR="~/robocomp/components/"
branches:
  - euroage*
script:
  - ls robocomp/components/euroage-tv/components/tvgames/
