//******************************************************************
// 
//  Generated by RoboCompDSL
//  
//  File name: integratedHand.ice
//  Source: integratedHand.idsl
//  
//****************************************************************** 
