//******************************************************************
// 
//  Generated by RoboCompDSL
//  
//  File name: TvGames.ice
//  Source: TvGames.idsl
//  
//****************************************************************** 
#ifndef ROBOCOMPTVGAMES_ICE
#define ROBOCOMPTVGAMES_ICE
module RoboCompTvGames
{
	interface TvGames
	{
		void launchGame (string name);
	};
};

#endif
