# -*- coding: utf-8 -*-
# **********************************************************************
#
# Copyright (c) 2003-2018 ZeroC, Inc. All rights reserved.
#
# This copy of Ice is licensed to you under the terms described in the
# ICE_LICENSE file included in this distribution.
#
# **********************************************************************
#
# Ice version 3.7.1
#
# <auto-generated>
#
# Generated from file `GameMetrics.ice'
#
# Warning: do not edit this file.
#
# </auto-generated>
#

from sys import version_info as _version_info_
import Ice, IcePy

# Start of module EuroAgeGamesMetrics
_M_EuroAgeGamesMetrics = Ice.openModule('EuroAgeGamesMetrics')
__name__ = 'EuroAgeGamesMetrics'

if 'StatusType' not in _M_EuroAgeGamesMetrics.__dict__:
    _M_EuroAgeGamesMetrics.StatusType = Ice.createTempClass()
    class StatusType(Ice.EnumBase):

        def __init__(self, _n, _v):
            Ice.EnumBase.__init__(self, _n, _v)

        def valueOf(self, _n):
            if _n in self._enumerators:
                return self._enumerators[_n]
            return None
        valueOf = classmethod(valueOf)

    StatusType.waiting = StatusType("waiting", 0)
    StatusType.initializing = StatusType("initializing", 1)
    StatusType.initialized = StatusType("initialized", 2)
    StatusType.playing = StatusType("playing", 3)
    StatusType.paused = StatusType("paused", 4)
    StatusType.continued = StatusType("continued", 5)
    StatusType.win = StatusType("win", 6)
    StatusType.lose = StatusType("lose", 7)
    StatusType._enumerators = { 0:StatusType.waiting, 1:StatusType.initializing, 2:StatusType.initialized, 3:StatusType.playing, 4:StatusType.paused, 5:StatusType.continued, 6:StatusType.win, 7:StatusType.lose }

    _M_EuroAgeGamesMetrics._t_StatusType = IcePy.defineEnum('::EuroAgeGamesMetrics::StatusType', StatusType, (), StatusType._enumerators)

    _M_EuroAgeGamesMetrics.StatusType = StatusType
    del StatusType

if 'Status' not in _M_EuroAgeGamesMetrics.__dict__:
    _M_EuroAgeGamesMetrics.Status = Ice.createTempClass()
    class Status(object):
        def __init__(self, currentStatus=_M_EuroAgeGamesMetrics.StatusType.waiting, date=''):
            self.currentStatus = currentStatus
            self.date = date

        def __hash__(self):
            _h = 0
            _h = 5 * _h + Ice.getHash(self.currentStatus)
            _h = 5 * _h + Ice.getHash(self.date)
            return _h % 0x7fffffff

        def __compare(self, other):
            if other is None:
                return 1
            elif not isinstance(other, _M_EuroAgeGamesMetrics.Status):
                return NotImplemented
            else:
                if self.currentStatus is None or other.currentStatus is None:
                    if self.currentStatus != other.currentStatus:
                        return (-1 if self.currentStatus is None else 1)
                else:
                    if self.currentStatus < other.currentStatus:
                        return -1
                    elif self.currentStatus > other.currentStatus:
                        return 1
                if self.date is None or other.date is None:
                    if self.date != other.date:
                        return (-1 if self.date is None else 1)
                else:
                    if self.date < other.date:
                        return -1
                    elif self.date > other.date:
                        return 1
                return 0

        def __lt__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r < 0

        def __le__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r <= 0

        def __gt__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r > 0

        def __ge__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r >= 0

        def __eq__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r == 0

        def __ne__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r != 0

        def __str__(self):
            return IcePy.stringify(self, _M_EuroAgeGamesMetrics._t_Status)

        __repr__ = __str__

    _M_EuroAgeGamesMetrics._t_Status = IcePy.defineStruct('::EuroAgeGamesMetrics::Status', Status, (), (
        ('currentStatus', (), _M_EuroAgeGamesMetrics._t_StatusType),
        ('date', (), IcePy._t_string)
    ))

    _M_EuroAgeGamesMetrics.Status = Status
    del Status

if 'Position' not in _M_EuroAgeGamesMetrics.__dict__:
    _M_EuroAgeGamesMetrics.Position = Ice.createTempClass()
    class Position(object):
        def __init__(self, x=0.0, y=0.0):
            self.x = x
            self.y = y

        def __eq__(self, other):
            if other is None:
                return False
            elif not isinstance(other, _M_EuroAgeGamesMetrics.Position):
                return NotImplemented
            else:
                if self.x != other.x:
                    return False
                if self.y != other.y:
                    return False
                return True

        def __ne__(self, other):
            return not self.__eq__(other)

        def __str__(self):
            return IcePy.stringify(self, _M_EuroAgeGamesMetrics._t_Position)

        __repr__ = __str__

    _M_EuroAgeGamesMetrics._t_Position = IcePy.defineStruct('::EuroAgeGamesMetrics::Position', Position, (), (
        ('x', (), IcePy._t_float),
        ('y', (), IcePy._t_float)
    ))

    _M_EuroAgeGamesMetrics.Position = Position
    del Position

if 'Metrics' not in _M_EuroAgeGamesMetrics.__dict__:
    _M_EuroAgeGamesMetrics.Metrics = Ice.createTempClass()
    class Metrics(object):
        def __init__(self, currentDate='', pos=Ice._struct_marker, screenTouched=False, handClosed=False, numHelps=0, numChecked=0, numHits=0, numFails=0):
            self.currentDate = currentDate
            if pos is Ice._struct_marker:
                self.pos = _M_EuroAgeGamesMetrics.Position()
            else:
                self.pos = pos
            self.screenTouched = screenTouched
            self.handClosed = handClosed
            self.numHelps = numHelps
            self.numChecked = numChecked
            self.numHits = numHits
            self.numFails = numFails

        def __eq__(self, other):
            if other is None:
                return False
            elif not isinstance(other, _M_EuroAgeGamesMetrics.Metrics):
                return NotImplemented
            else:
                if self.currentDate != other.currentDate:
                    return False
                if self.pos != other.pos:
                    return False
                if self.screenTouched != other.screenTouched:
                    return False
                if self.handClosed != other.handClosed:
                    return False
                if self.numHelps != other.numHelps:
                    return False
                if self.numChecked != other.numChecked:
                    return False
                if self.numHits != other.numHits:
                    return False
                if self.numFails != other.numFails:
                    return False
                return True

        def __ne__(self, other):
            return not self.__eq__(other)

        def __str__(self):
            return IcePy.stringify(self, _M_EuroAgeGamesMetrics._t_Metrics)

        __repr__ = __str__

    _M_EuroAgeGamesMetrics._t_Metrics = IcePy.defineStruct('::EuroAgeGamesMetrics::Metrics', Metrics, (), (
        ('currentDate', (), IcePy._t_string),
        ('pos', (), _M_EuroAgeGamesMetrics._t_Position),
        ('screenTouched', (), IcePy._t_bool),
        ('handClosed', (), IcePy._t_bool),
        ('numHelps', (), IcePy._t_int),
        ('numChecked', (), IcePy._t_int),
        ('numHits', (), IcePy._t_int),
        ('numFails', (), IcePy._t_int)
    ))

    _M_EuroAgeGamesMetrics.Metrics = Metrics
    del Metrics

_M_EuroAgeGamesMetrics._t_GameMetrics = IcePy.defineValue('::EuroAgeGamesMetrics::GameMetrics', Ice.Value, -1, (), False, True, None, ())

if 'GameMetricsPrx' not in _M_EuroAgeGamesMetrics.__dict__:
    _M_EuroAgeGamesMetrics.GameMetricsPrx = Ice.createTempClass()
    class GameMetricsPrx(Ice.ObjectPrx):

        def metricsObtained(self, m, context=None):
            return _M_EuroAgeGamesMetrics.GameMetrics._op_metricsObtained.invoke(self, ((m, ), context))

        def metricsObtainedAsync(self, m, context=None):
            return _M_EuroAgeGamesMetrics.GameMetrics._op_metricsObtained.invokeAsync(self, ((m, ), context))

        def begin_metricsObtained(self, m, _response=None, _ex=None, _sent=None, context=None):
            return _M_EuroAgeGamesMetrics.GameMetrics._op_metricsObtained.begin(self, ((m, ), _response, _ex, _sent, context))

        def end_metricsObtained(self, _r):
            return _M_EuroAgeGamesMetrics.GameMetrics._op_metricsObtained.end(self, _r)

        def statusChanged(self, s, context=None):
            return _M_EuroAgeGamesMetrics.GameMetrics._op_statusChanged.invoke(self, ((s, ), context))

        def statusChangedAsync(self, s, context=None):
            return _M_EuroAgeGamesMetrics.GameMetrics._op_statusChanged.invokeAsync(self, ((s, ), context))

        def begin_statusChanged(self, s, _response=None, _ex=None, _sent=None, context=None):
            return _M_EuroAgeGamesMetrics.GameMetrics._op_statusChanged.begin(self, ((s, ), _response, _ex, _sent, context))

        def end_statusChanged(self, _r):
            return _M_EuroAgeGamesMetrics.GameMetrics._op_statusChanged.end(self, _r)

        @staticmethod
        def checkedCast(proxy, facetOrContext=None, context=None):
            return _M_EuroAgeGamesMetrics.GameMetricsPrx.ice_checkedCast(proxy, '::EuroAgeGamesMetrics::GameMetrics', facetOrContext, context)

        @staticmethod
        def uncheckedCast(proxy, facet=None):
            return _M_EuroAgeGamesMetrics.GameMetricsPrx.ice_uncheckedCast(proxy, facet)

        @staticmethod
        def ice_staticId():
            return '::EuroAgeGamesMetrics::GameMetrics'
    _M_EuroAgeGamesMetrics._t_GameMetricsPrx = IcePy.defineProxy('::EuroAgeGamesMetrics::GameMetrics', GameMetricsPrx)

    _M_EuroAgeGamesMetrics.GameMetricsPrx = GameMetricsPrx
    del GameMetricsPrx

    _M_EuroAgeGamesMetrics.GameMetrics = Ice.createTempClass()
    class GameMetrics(Ice.Object):

        def ice_ids(self, current=None):
            return ('::EuroAgeGamesMetrics::GameMetrics', '::Ice::Object')

        def ice_id(self, current=None):
            return '::EuroAgeGamesMetrics::GameMetrics'

        @staticmethod
        def ice_staticId():
            return '::EuroAgeGamesMetrics::GameMetrics'

        def metricsObtained(self, m, current=None):
            raise NotImplementedError("servant method 'metricsObtained' not implemented")

        def statusChanged(self, s, current=None):
            raise NotImplementedError("servant method 'statusChanged' not implemented")

        def __str__(self):
            return IcePy.stringify(self, _M_EuroAgeGamesMetrics._t_GameMetricsDisp)

        __repr__ = __str__

    _M_EuroAgeGamesMetrics._t_GameMetricsDisp = IcePy.defineClass('::EuroAgeGamesMetrics::GameMetrics', GameMetrics, (), None, ())
    GameMetrics._ice_type = _M_EuroAgeGamesMetrics._t_GameMetricsDisp

    GameMetrics._op_metricsObtained = IcePy.Operation('metricsObtained', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), _M_EuroAgeGamesMetrics._t_Metrics, False, 0),), (), None, ())
    GameMetrics._op_statusChanged = IcePy.Operation('statusChanged', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), _M_EuroAgeGamesMetrics._t_Status, False, 0),), (), None, ())

    _M_EuroAgeGamesMetrics.GameMetrics = GameMetrics
    del GameMetrics

# End of module EuroAgeGamesMetrics
