# -*- coding: utf-8 -*-
# **********************************************************************
#
# Copyright (c) 2003-2018 ZeroC, Inc. All rights reserved.
#
# This copy of Ice is licensed to you under the terms described in the
# ICE_LICENSE file included in this distribution.
#
# **********************************************************************
#
# Ice version 3.7.1
#
# <auto-generated>
#
# Generated from file `TouchPoints.ice'
#
# Warning: do not edit this file.
#
# </auto-generated>
#

from sys import version_info as _version_info_
import Ice, IcePy

# Start of module RoboCompTouchPoints
_M_RoboCompTouchPoints = Ice.openModule('RoboCompTouchPoints')
__name__ = 'RoboCompTouchPoints'

if '_t_KeyPoint' not in _M_RoboCompTouchPoints.__dict__:
    _M_RoboCompTouchPoints._t_KeyPoint = IcePy.defineSequence('::RoboCompTouchPoints::KeyPoint', (), IcePy._t_int)

if 'StateEnum' not in _M_RoboCompTouchPoints.__dict__:
    _M_RoboCompTouchPoints.StateEnum = Ice.createTempClass()
    class StateEnum(Ice.EnumBase):

        def __init__(self, _n, _v):
            Ice.EnumBase.__init__(self, _n, _v)

        def valueOf(self, _n):
            if _n in self._enumerators:
                return self._enumerators[_n]
            return None
        valueOf = classmethod(valueOf)

    StateEnum.TouchPointPressed = StateEnum("TouchPointPressed", 0)
    StateEnum.TouchPointMoved = StateEnum("TouchPointMoved", 1)
    StateEnum.TouchPointStationary = StateEnum("TouchPointStationary", 2)
    StateEnum.TouchPointReleased = StateEnum("TouchPointReleased", 3)
    StateEnum._enumerators = { 0:StateEnum.TouchPointPressed, 1:StateEnum.TouchPointMoved, 2:StateEnum.TouchPointStationary, 3:StateEnum.TouchPointReleased }

    _M_RoboCompTouchPoints._t_StateEnum = IcePy.defineEnum('::RoboCompTouchPoints::StateEnum', StateEnum, (), StateEnum._enumerators)

    _M_RoboCompTouchPoints.StateEnum = StateEnum
    del StateEnum

if 'TouchPoint' not in _M_RoboCompTouchPoints.__dict__:
    _M_RoboCompTouchPoints.TouchPoint = Ice.createTempClass()
    class TouchPoint(object):
        def __init__(self, id=0, state=_M_RoboCompTouchPoints.StateEnum.TouchPointPressed, fingertip=None, lastPos=None):
            self.id = id
            self.state = state
            self.fingertip = fingertip
            self.lastPos = lastPos

        def __hash__(self):
            _h = 0
            _h = 5 * _h + Ice.getHash(self.id)
            _h = 5 * _h + Ice.getHash(self.state)
            if self.fingertip:
                for _i0 in self.fingertip:
                    _h = 5 * _h + Ice.getHash(_i0)
            if self.lastPos:
                for _i1 in self.lastPos:
                    _h = 5 * _h + Ice.getHash(_i1)
            return _h % 0x7fffffff

        def __compare(self, other):
            if other is None:
                return 1
            elif not isinstance(other, _M_RoboCompTouchPoints.TouchPoint):
                return NotImplemented
            else:
                if self.id is None or other.id is None:
                    if self.id != other.id:
                        return (-1 if self.id is None else 1)
                else:
                    if self.id < other.id:
                        return -1
                    elif self.id > other.id:
                        return 1
                if self.state is None or other.state is None:
                    if self.state != other.state:
                        return (-1 if self.state is None else 1)
                else:
                    if self.state < other.state:
                        return -1
                    elif self.state > other.state:
                        return 1
                if self.fingertip is None or other.fingertip is None:
                    if self.fingertip != other.fingertip:
                        return (-1 if self.fingertip is None else 1)
                else:
                    if self.fingertip < other.fingertip:
                        return -1
                    elif self.fingertip > other.fingertip:
                        return 1
                if self.lastPos is None or other.lastPos is None:
                    if self.lastPos != other.lastPos:
                        return (-1 if self.lastPos is None else 1)
                else:
                    if self.lastPos < other.lastPos:
                        return -1
                    elif self.lastPos > other.lastPos:
                        return 1
                return 0

        def __lt__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r < 0

        def __le__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r <= 0

        def __gt__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r > 0

        def __ge__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r >= 0

        def __eq__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r == 0

        def __ne__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r != 0

        def __str__(self):
            return IcePy.stringify(self, _M_RoboCompTouchPoints._t_TouchPoint)

        __repr__ = __str__

    _M_RoboCompTouchPoints._t_TouchPoint = IcePy.defineStruct('::RoboCompTouchPoints::TouchPoint', TouchPoint, (), (
        ('id', (), IcePy._t_int),
        ('state', (), _M_RoboCompTouchPoints._t_StateEnum),
        ('fingertip', (), _M_RoboCompTouchPoints._t_KeyPoint),
        ('lastPos', (), _M_RoboCompTouchPoints._t_KeyPoint)
    ))

    _M_RoboCompTouchPoints.TouchPoint = TouchPoint
    del TouchPoint

if '_t_TouchPointsSeq' not in _M_RoboCompTouchPoints.__dict__:
    _M_RoboCompTouchPoints._t_TouchPointsSeq = IcePy.defineSequence('::RoboCompTouchPoints::TouchPointsSeq', (), _M_RoboCompTouchPoints._t_TouchPoint)

_M_RoboCompTouchPoints._t_TouchPoints = IcePy.defineValue('::RoboCompTouchPoints::TouchPoints', Ice.Value, -1, (), False, True, None, ())

if 'TouchPointsPrx' not in _M_RoboCompTouchPoints.__dict__:
    _M_RoboCompTouchPoints.TouchPointsPrx = Ice.createTempClass()
    class TouchPointsPrx(Ice.ObjectPrx):

        def detectedTouchPoints(self, touchpoints, context=None):
            return _M_RoboCompTouchPoints.TouchPoints._op_detectedTouchPoints.invoke(self, ((touchpoints, ), context))

        def detectedTouchPointsAsync(self, touchpoints, context=None):
            return _M_RoboCompTouchPoints.TouchPoints._op_detectedTouchPoints.invokeAsync(self, ((touchpoints, ), context))

        def begin_detectedTouchPoints(self, touchpoints, _response=None, _ex=None, _sent=None, context=None):
            return _M_RoboCompTouchPoints.TouchPoints._op_detectedTouchPoints.begin(self, ((touchpoints, ), _response, _ex, _sent, context))

        def end_detectedTouchPoints(self, _r):
            return _M_RoboCompTouchPoints.TouchPoints._op_detectedTouchPoints.end(self, _r)

        @staticmethod
        def checkedCast(proxy, facetOrContext=None, context=None):
            return _M_RoboCompTouchPoints.TouchPointsPrx.ice_checkedCast(proxy, '::RoboCompTouchPoints::TouchPoints', facetOrContext, context)

        @staticmethod
        def uncheckedCast(proxy, facet=None):
            return _M_RoboCompTouchPoints.TouchPointsPrx.ice_uncheckedCast(proxy, facet)

        @staticmethod
        def ice_staticId():
            return '::RoboCompTouchPoints::TouchPoints'
    _M_RoboCompTouchPoints._t_TouchPointsPrx = IcePy.defineProxy('::RoboCompTouchPoints::TouchPoints', TouchPointsPrx)

    _M_RoboCompTouchPoints.TouchPointsPrx = TouchPointsPrx
    del TouchPointsPrx

    _M_RoboCompTouchPoints.TouchPoints = Ice.createTempClass()
    class TouchPoints(Ice.Object):

        def ice_ids(self, current=None):
            return ('::Ice::Object', '::RoboCompTouchPoints::TouchPoints')

        def ice_id(self, current=None):
            return '::RoboCompTouchPoints::TouchPoints'

        @staticmethod
        def ice_staticId():
            return '::RoboCompTouchPoints::TouchPoints'

        def detectedTouchPoints(self, touchpoints, current=None):
            raise NotImplementedError("servant method 'detectedTouchPoints' not implemented")

        def __str__(self):
            return IcePy.stringify(self, _M_RoboCompTouchPoints._t_TouchPointsDisp)

        __repr__ = __str__

    _M_RoboCompTouchPoints._t_TouchPointsDisp = IcePy.defineClass('::RoboCompTouchPoints::TouchPoints', TouchPoints, (), None, ())
    TouchPoints._ice_type = _M_RoboCompTouchPoints._t_TouchPointsDisp

    TouchPoints._op_detectedTouchPoints = IcePy.Operation('detectedTouchPoints', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), _M_RoboCompTouchPoints._t_TouchPointsSeq, False, 0),), (), None, ())

    _M_RoboCompTouchPoints.TouchPoints = TouchPoints
    del TouchPoints

# End of module RoboCompTouchPoints
